spring:
  application:
    name: order
server:
  port: 7001
eureka:
  client:
    ###集群模式为true
    register-with-eureka: false
    ###是否检索服务信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enable: false

