spring:
  application:
    name: server
server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.1.3
  client:
    ###集群模式为true
    register-with-eureka: false
    ###是否检索服务信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-replicated-request-compression: false
#    eviction-interval-timer-in-ms: 2000