spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: metadata_routh
#        uri: http://localhost:8082
        uri: lb://metadata
        predicates:
        - Path=/metadata/**
#       集群部署配置多次，可以达到负载均衡
#      - id: metadata_routh
#        uri: lb://metadata
#        predicates:
#        - Path=/metadata/**
server:
  port: 9527
management:
  endpoints:
    web:
      exposure:
        include: '*'


