spring:
  application:
    name: gateway
server:
  port: 9527
eureka:
  client:
    ###集群模式为true
    register-with-eureka: true
    ###是否检索服务信息
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/


