spring:
  application:
    name: data-standard
server:
  port: 8081
  servlet:
    context-path: /dataStandard
eureka:
  client:
    ###集群模式为true
    register-with-eureka: true
    ###是否检索服务信息
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.1.3:7001/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enable: false

